# Generated by Django 5.1.4 on 2024-12-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_profile_level_profile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_requirement', models.PositiveIntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badge_icons/')),
            ],
        ),
    ]
