# Generated by Django 5.1.4 on 2024-12-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_location_post_location_name_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
