# Generated by Django 5.1.4 on 2024-12-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_post_latitude_alter_post_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='backend.tag'),
        ),
    ]
