# Generated by Django 5.1.4 on 2024-12-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_group_groupmessage_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
