# Generated by Django 5.1.1 on 2024-12-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
