# Generated by Django 5.1.4 on 2024-12-20 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_sharedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='admins',
            field=models.ManyToManyField(related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
