# Generated by Django 5.1.4 on 2024-12-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
