"""
Django settings for VoyageView project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3-+0*o#bp)ool@8f)c30owh_p-&)lgqqoft&r^gmj6pd_ft0zu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Access token süresi: 30 dakika
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token süresi: 7 gün
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}

ROOT_URLCONF = 'VoyageView.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'voyageview.asgi.application'

WSGI_APPLICATION = 'VoyageView.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,  # Sayfa başına gösterilecek yorum sayısı
    
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'voyageview_db',
        'USER': 'postgres',
        'PASSWORD': 'cgr2001ZY',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'tr'  # Türkçe dil kodu
TIME_ZONE = 'Europe/Istanbul'  # Türkiye saat dilimi

USE_I18N = True
USE_L10N = True  # Yerel tarih/saat biçimi
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "VoyageView Admin",
    "site_header": "VoyageView Admin Paneli",
    "site_brand": "VoyageView",
    "site_logo": "your_logo_path/logo.png",  # Logo eklemek için bir dosya yolu
    "welcome_sign": "VoyageView'e Hoş Geldiniz!",
    "copyright": "VoyageView 2024",
    "search_model": "backend.Post",  # Arama çubuğu modeli
    "user_avatar": "profile_image",  # Kullanıcı profil resmi
    "topmenu_links": [
        {"name": "Anasayfa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "VoyageView", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        {"model": "auth.user"},
        {"name": "Desteğe Git", "url": "https://support.voyageview.com", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "backend.Profile": "fas fa-user",
        "backend.Post": "fas fa-newspaper",
        "backend.Comment": "fas fa-comments",
        "backend.Notification": "fas fa-bell",
        "backend.Report": "fas fa-flag",
    },
    "order_with_respect_to": ["auth", "backend", "backend.Post", "backend.Comment"],
    "language_chooser": True,
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # TLS için doğru port
EMAIL_USE_TLS = True  # TLS kullanımı açık
EMAIL_HOST_USER = 'cagriozay13@gmail.com'
EMAIL_HOST_PASSWORD = 'wndjgpodtsiizwqy'  # Gmail uygulama şifresi kullanmanız önerilir
