# Generated by Django 5.1.4 on 2025-01-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_cover_image_blogpost_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_covers/'),
        ),
    ]
