# Generated by Django 5.1.4 on 2025-01-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_is_approved_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_media/'),
        ),
    ]
