# Generated by Django 5.1.4 on 2025-01-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_readinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=41.0082, max_digits=9),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='location',
            field=models.CharField(default='İstanbul, Türkiye', help_text='Yazının konumu (Örn: İstanbul, Türkiye)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=28.9784, max_digits=9),
        ),
    ]
