# Generated by Django 5.1.4 on 2025-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_latitude_blogpost_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='location_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
