# Generated by Django 5.1.4 on 2025-01-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_category_post_count_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('PUBLISHED', 'Yayında'), ('REJECTED', 'Reddedildi')], default='DRAFT', max_length=20),
        ),
    ]
