# Generated by Django 5.1.4 on 2025-01-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=41.0082, max_digits=9),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='İstanbul, Türkiye', help_text='Yaşadığınız şehir/ülke', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=28.9784, max_digits=9),
        ),
    ]
