# Generated by Django 5.1.4 on 2025-01-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
